# This file contains values from Cookiecutter

default_context:
  project_name: "check_reqs"
  project_description: "Checks if all requirements from a file are installed in the current Python env"
  organization: "renefritze"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "renefritze"
  email: "coding@fritze.me"
  version: "0.1.0"
  line_length: "119"
  create_example_template: "cli"
